---
version: 2025.1.2
scanners:
  enabled: []
  disabled: []
  overrides:
    values.yaml: YAMLScanner
fail_on: high
exclude:
  paths:
    - node_modules/
    - venv/
    - .venv/
    - env/
    - .git/
    - .svn/
    - __pycache__/
    - '*.egg-info/'
    - dist/
    - build/
    - .tox/
    - .pytest_cache/
    - .mypy_cache/
  files:
    - '*.min.js'
    - '*.min.css'
    - '*.bundle.js'
    - '*.map'
ide:
  claude_code:
    enabled: false
    auto_scan: true
    inline_annotations: true
  cursor:
    enabled: false
  vscode:
    enabled: false
  gemini_cli:
    enabled: false
workers: null
cache_enabled: true
